INSERT INTO `paises` (`cod_pais`, `nome`,`sigla`) VALUES
('4','Afeganistão','AFG'),
('248','Ilhas Åland','ALA'),
('8','Albânia','ALB'),
('12','Argélia','DZA'),
('16','American Samoa','ASM'),
('20','Andorra','AND'),
('24','Angola','AGO'),
('660','Anguilla','AIA'),
('28','Antígua e Barbuda','ATG'),
('32','Argentina','ARG'),
('51','Armenia','ARM'),
('533','Aruba','ABW'),
('36','Austrália','AUS'),
('40','Áustria','AUT'),
('31','Azerbaijão','AZE'),
('44','Bahamas','BHS'),
('48','Bahrain','BHR'),
('50','Bangladesh','BGD'),
('52','Barbados','BRB'),
('112','Belarus','BLR'),
('56','Bélgica','BEL'),
('84','Belize','BLZ'),
('204','Benin','BEN'),
('60','Bermuda','BMU'),
('64','Butão','BTN'),
('68','Bolívia (Estado Plurinacional da)','BOL'),
('535','Bonaire, Santo Eustáquio e Saba','BES'),
('70','a Bósnia e Herzegovina','BIH'),
('72','Botswana','BWA'),
('76','Brasil','BRA'),
('92','British Virgin Islands','VGB'),
('96','Brunei Darussalam','BRN'),
('100','Bulgária','BGR'),
('854','Burkina Faso','BFA'),
('108','Burundi','BDI'),
('132','Cabo Verde','CPV'),
('116','Cambodia','KHM'),
('120','Camarões','CMR'),
('124','Canadá','CAN'),
('136','Ilhas Cayman','CYM'),
('140','Central Africano República','CAF'),
('148','Chad','TCD'),
('830','Channel Islands',''),
('152','Chile','CHL'),
('156','China','CHN'),
('344','China, Hong Kong Região Administrativa Especial','HKG'),
('446','China, Região Administrativa Especial de Macau','MAC'),
('170','Colômbia','COL'),
('174','Comores','COM'),
('178','Congo','COG'),
('184','Ilhas Cook','COK'),
('188','Costa Rica','CRI'),
('384','Costa do Marfim','CIV'),
('191','Croácia','VFC'),
('192','Cuba','CUB'),
('531','Curaçao','TCU'),
('196','Chipre','CYP'),
('203','República Checa','CZE'),
('408','República Popular Democrática da Coreia','PRK'),
('180','República Democrática do Congo','COD'),
('208','Dinamarca','DNK'),
('262','Djibouti','DJI'),
('212','Dominica','DMA'),
('214','República Dominicana','DOM ​​'),
('218','Equador','ECU'),
('818','Egito','EGY'),
('222','El Salvador','SLV'),
('226','Guiné Equatorial','QNG'),
('232','Eritreia','IIE'),
('233','Estónia','EST'),
('231','Ethiopia','ETH'),
('234','Ilhas Faroé','FRO'),
('238','Ilhas Falkland (Malvinas)','FLK'),
('242','Fiji','FJI'),
('246','Finlândia','FIN'),
('250','França','FRA'),
('254','Guiana Francesa','GUF'),
('258','Polinésia Francesa','PYF'),
('266','Gabão','GAB'),
('270','Gambia','GMB'),
('268','Georgia','GEO'),
('276','Alemanha','DEU'),
('288','Ghana','GHA'),
('292','Gibraltar','GIB'),
('300','Grécia','GRC'),
('304','Groenlândia','GRL'),
('308','Granada','GRD'),
('312','Guadalupe','GLP'),
('316','de Guam','GUM'),
('320','Guatemala','GTM'),
('831','Guernsey','GGY'),
('324','Guiné','GIN'),
('624','Guiné-Bissau','GNB'),
('328','Guyana','GUY'),
('332','Haiti','HTI'),
('336','Santa Sé', 'IVA'),
('340','Honduras','HND'),
('348','Hungria','HUN'),
('352','Islândia','ISL'),
('356','Índia','IND'),
('360','Indonésia','IDN'),
('364','Irão (República Islâmica do)','IRN'),
('368','Iraque','IRQ'),
('372','Portugal','IRL'),
('833','Isle of Man','IMN'),
('376','Israel','ISR'),
('380','Itália','ITA'),
('388','Jamaica','JAM'),
('392','Japão','JPN'),
('832','Jersey','JEY'),
('400','Jordan','JOR'),
('398','Cazaquistão','KAZ'),
('404','Quênia','KEN'),
('296','Kiribati','KIR'),
('414','Kuwait','KWT'),
('417','Quirguistão','KGZ'),
('418','República Democrática Popular do Laos','LAO'),
('428','Letónia','LVA'),
('422','Líbano','LBN'),
('426','Lesotho','LSO'),
('430','Libéria','LBR'),
('434','Líbia','LBY'),
('438','Liechtenstein','LIE'),
('440','Lituânia','LTU'),
('442','Luxemburgo','LUX'),
('450','Madagascar','ODM'),
('454','Malawi','MWI'),
('458','Malásia','MYS'),
('462','Maldivas','MDV'),
('466','Mali','MLI'),
('470','Malta','MLT'),
('584','Ilhas Marshall','MHL'),
('474','Martinique','MTQ'),
('478','Mauritânia','MRT'),
('480','Maurícias','MUS'),
('175','Mayotte','MYT'),
('484','México','MEX'),
('583','Micronésia (Estados Federados da)','FSM'),
('492','Monaco','MCO'),
('496','Mongólia','MNG'),
('499','Montenegro','MNE'),
('500','Montserrat','MSR'),
('504','Marrocos','MAR'),
('508','Moçambique','MOZ'),
('104','Myanmar','MMR'),
('516','Namíbia','NAM'),
('520','Nauru','NRU'),
('524','Nepal','NPL'),
('528','Holanda','NLD'),
('540','New Caledonia','NCL'),
('554','Nova Zelândia','NZL'),
('558','Nicarágua','NIC'),
('562','Niger','NER'),
('566','Nigéria','SNG'),
('570','Niue','NIU'),
('574','Ilha Norfolk','NFK'),
('580','Northern Mariana Islands','MNP'),
('578','Noruega','NOR'),
('512','Oman','OMN'),
('586','Paquistão','PAK'),
('585','Palau','PLW'),
('591','Panama','PAN'),
('598','Papua-Nova Guiné','PNG'),
('600','Paraguai','PRY'),
('604','Peru','PER'),
('608','Filipinas','PHL'),
('612','Pitcairn','PCN'),
('616','Polónia','POL'),
('620','Portugal','PRT'),
('630','Puerto Rico','PRI'),
('634','Qatar','QAT'),
('410','República da Coreia','KOR'),
('498','República da Moldávia','MDA'),
('638','Reunião','REU'),
('642','Romania','ROU'),
('643','Rússia','RUS'),
('646','Ruanda','RWA'),
('652','São Bartolomeu','BLM'),
('654','Santa Helena','SHN'),
('659','São Cristóvão e Nevis','KNA'),
('662','Santa Lúcia','LCA'),
('663','Saint Martin (parte francesa)','MAF'),
('666','São Pedro e Miquelon','SPM'),
('670','São Vicente e Granadinas','VCT'),
('882','Samoa','WSM'),
('674','San Marino','SMR'),
('678','São Tomé e Príncipe','STP'),
('680','Sark',''),
('682','Arábia Saudita','SAU'),
('686','Senegal','SEN'),
('688','Sérvia','SRB'),
('690','Seychelles','SYC'),
('694','Serra Leoa','LES'),
('702','Cingapura','PEC'),
('534','Sint Maarten (parte holandesa)','SXM'),
('703','Eslováquia','SVK'),
('705','Slovenia','SVN'),
('90','Ilhas Salomão','SLB'),
('706','Somália','SOM'),
('710','África do Sul','ZAF'),
('728','Sudão do Sul','SSD'),
('724','Espanha','ESP'),
('144','Sri Lanka','LKA'),
('275','Estado da Palestina','PSE'),
('729','Sudão','SDN'),
('740','Suriname','SUR'),
('744','Svalbard e Jan Mayen','SJM'),
('748','Suazilândia','SWZ'),
('752','Suécia','SWE'),
('756','Suíça','CHE'),
('760','República Árabe Síria','SYR'),
('762','Tajiquistão','TJK'),
('764','Tailândia','THA'),
('807','A antiga República jugoslava da Macedónia','MKD'),
('626','Timor-Leste','TLS'),
('768','Togo','TGO'),
('772','Tokelau','TKL'),
('776','Tonga','TON'),
('780','Trinidad e Tobago','TTO'),
('788','Tunísia','TUN'),
('792','a Turquia','TUR'),
('795','Turcomenistão','TKM'),
('796','Ilhas Turks e Caicos','TCA'),
('798','Tuvalu','TUV'),
('800','Uganda','UGA'),
('804','Ucrânia','UKR'),
('784','Emirados Árabes Unidos','ARE'),
('826','Reino Unido da Grã-Bretanha e Irlanda do Norte','GBR'),
('834','República Unida da Tanzânia','TZA'),
('840','Estados Unidos da América','EUA'),
('850','United States Virgin Islands','VIR'),
('858','Uruguai','URY'),
('860','Uzbequistão','UZB'),
('548','Vanuatu','VUT'),
('862','Venezuela (República Bolivariana da)','VEN'),
('704','Viet Nam','VNM'),
('876','Ilhas Wallis e Futuna','WLF'),
('732','Sahara Ocidental','ESH'),
('887','Yemen','YEM'),
('894','Zâmbia','ZMB'),
('716','Zimbabwe','ZWE');
